name: Build and deploy app as Docker Image

on:
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/pcpartradar:latest .
      
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/pcpartradar:latest